### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by markborkum** [Megultron/Ruby-PeakList-Library#3]
Add runtime and development dependencies to the Gem specification (see: [Patterns - RubyGems Guides](http://guides.rubygems.org/patterns/#declaring-dependencies)).

In theory, you should only need a runtime dependency for Nokogiri.

Once this is done, remove the line `require 'rubygems'` from `peak_list_parser.rb`.

**Comment by Megultron** [comment]
(Hopefully) fixed with 83e211f8a89303011fe57691e1f3a3f34ff8af59
