### ISSUE TITLE
Casting

### ISSUE THREAD

**Issue by markborkum** [Megultron/Ruby-PeakList-Library#4]
In `peak_list_parser.rb` there are calls to the `Nokogiri::XML::Searchable#at_css` function. 

The type of the return value (e.g., node, node-set and attribute) of `#at_css` is determined by the semantics of the specified selector.

Please cast the values to the appropriate type (e.g., `String`, `Fixnum` and `Float`).

**Comment by Megultron** [comment]
Fixed with commit 6384c613766341741acfcad5bb481505cb8bf371

**Comment by markborkum** [comment]
Casting should be performed by the parser, not by the constructor.

**Comment by Megultron** [comment]
Good point. Should be fixed with commit c70709f471cf7851ee096aefa09004fad18e7af7
