### ISSUE TITLE
Inaccessible Instance Variables

### ISSUE THREAD

**Issue by markborkum** [Megultron/Ruby-PeakList-Library#5]
Currently, there is no way for "unfriendly" code (C++ pun...) to access the instance variables of `PeakList`, `Peak`, etc.

Use the `attr_accessor` class-level function to declare the instance variables as attributes.

**Comment by Megultron** [comment]
Sure thing. Just do double-check, do you only want the data structures to be accessible, or would there be any case where outside code would need to interact with the parser itself beyond method-calling?

**Comment by markborkum** [comment]
Only the data structures.

Once the end-user has called
```ruby
peak_list = Bruker::XML::PLParser.parsePL(xmlDoc)
```
there should be no further need to interact with the parser.

**Comment by Megultron** [comment]
Excellent. Wanted to make sure I was on the same page about the primary use case.

**Comment by Megultron** [comment]
Fixed with commit 6384c613766341741acfcad5bb481505cb8bf371
