### ISSUE TITLE
(Non)Correspondence between Class and Node names

### ISSUE THREAD

**Issue by markborkum** [Megultron/Ruby-PeakList-Library#7]
Class names and node names should be equivalent (and should explicitly state the "dimensionality" of the corresponding entity).

- [x] Rename `ListHeader` to `PeakList1DHeader`.
- [x] Rename `PeakList` to `PeakList1D`.
- [x] Rename `Peak` to `Peak1D`.
- [x] Rename `PickDetails` to `PeakPickDetails`.

**Comment by Megultron** [comment]
Fixed with commit de2ec2250d1584edefb0ed37486aece179437b2c

**Comment by Megultron** [comment]
Fixed with commit de2ec2250d1584edefb0ed37486aece179437b2c
